export const COURSE = [
 {title:"Your role as a placement champion", sub:"Who does what, and where you fit", mins:"4 min",
  intro:"Placement success isn't the placement officer's job alone. In most colleges the work is shared between a central Training and Placement Officer, department faculty coordinators and student coordinators. Faculty are the bridge between what students can actually do and what recruiters need.",
  takeaways:["The TPO owns the calendar, recruiter relationships, operations and reporting. Faculty coordinators are usually the single point of contact for their department's students.","Your advantage is first-hand knowledge of each student — use it to spot gaps early and recommend the right fit.","This season you have four jobs: prepare students, organise drives, protect students, and keep them motivated."],
  toolkit:["Read your institute's placement policy end to end before the first drive.","List every eligible student in your department with a simple readiness status (ready / needs work / at risk).","Agree with the TPO, in writing, who handles which tasks this season."],
  check:{q:"Who is usually the single point of contact for a department's students during placements?",o:["The recruiter's HR team","The department faculty coordinator","The principal","Any senior student"],a:1},
  scenes:[
   {tag:"Module 1",title:"You're more than a recommendation letter",glyph:"🎓",points:["Prepare","Organise","Protect","Motivate"],say:"Welcome to Faculty Placement Champion by Core5. This course trains you to run placements alongside your students, not watch from the side. We'll cover four jobs: preparing students, organising drives, protecting them, and keeping them motivated."},
   {tag:"The team",title:"Who does what in a placement cell",glyph:"🏛️",points:["Training & Placement Officer","Faculty coordinators","Student coordinators","Recruiters"],say:"Most colleges split the work. The training and placement officer owns the calendar, recruiters and reporting. Department faculty coordinators are the single point of contact for their students. Student coordinators handle day-to-day logistics. Know exactly where you sit."},
   {tag:"Your edge",title:"You already know the students",glyph:"👩‍🏫",points:["Classroom insight","Project work","Attendance patterns"],say:"Faculty see students every day. You know who codes well, who freezes while presenting, and who has quietly stopped turning up. That insight is exactly what the placement office is missing."},
   {tag:"Make it count",title:"Turn insight into shared data",glyph:"🔗",points:["Readiness tracker","Portal profiles","Notes shared with the TPO"],say:"Insight only helps if it's shared. Record each student's readiness in the placement portal or a shared tracker, so the whole team can act on it before drives begin."}
  ]},
 {title:"Planning the season and the policy", sub:"Timelines, offer rules, tiers", mins:"5 min",
  intro:"Good seasons are decided months before the first company arrives. Student preparation should start roughly a year ahead, and the rules of the game — the placement policy — must be published and understood before anyone registers.",
  takeaways:["Serious preparation should start in pre-final year, with the final few months reserved for mock interviews, company research and aptitude drilling.","A written policy should cover registration, eligibility, offer rules, withdrawals, conduct and penalties.","Many institutes follow a one student, one offer rule, sometimes with a single dream-company attempt, and group companies into tiers or slots by package and role. Decide these before the season, not during it.","Brief students on the rules before they register; confusion mid-season turns into disputes."],
  toolkit:["Run a 30-minute policy briefing for your department and take attendance.","Publish a season calendar with tentative slot weeks.","Collect a signed policy acknowledgement from every registered student."],
  check:{q:"When should serious placement preparation ideally begin?",o:["A week before the first drive","After the first rejection","In pre-final year","Only once results are out"],a:2},
  scenes:[
   {tag:"Module 2",title:"The season starts a year early",glyph:"🗓️",points:["Pre-final year: foundations","Last 3 months: mocks & drills","Season: drives"],say:"Placement season is won early. Students should begin serious preparation in pre-final year, and spend the final three months before drives on mock interviews, company research and aptitude practice."},
   {tag:"Policy",title:"Write the rules down first",glyph:"📜",points:["Registration & eligibility","Offer rules","Withdrawal rules","Conduct & penalties"],say:"Every department needs a written placement policy. It should cover who can register, eligibility, offer rules, what happens if a student withdraws, and the code of conduct. Rules published in advance prevent fights later."},
   {tag:"Offer rules",title:"Rules you must be able to explain",glyph:"⚖️",points:["One student, one offer","Dream company option","Tiers by package & role"],say:"Many institutes follow a one student, one offer rule. Some allow a single dream-company attempt after a first offer, usually when the new package or brand is clearly better. Others group companies into tiers by salary and role. Whatever your institute uses, you must be able to explain it simply."},
   {tag:"Before registration",title:"Brief every student",glyph:"🗣️",points:["Policy session","Signed acknowledgement","One-page FAQ"],say:"Hold a short policy briefing before registration, collect a signed acknowledgement, and share a one-page FAQ. When a student later says nobody told me, you'll have the answer."}
  ]},
 {title:"Preparing students for every round", sub:"Resume, aptitude, GD, interviews", mins:"6 min",
  intro:"Most campus processes follow a predictable path: an aptitude or online test, sometimes a group discussion, technical interviews, and an HR round. Each tests something different, and each can be trained.",
  takeaways:["Resume: one clean page, tailored to the role, outcomes quantified, and nothing the student can't defend — interviewers probe every line.","Aptitude: short daily practice over months beats cramming. Use timed mocks and past papers, and review every mistake.","Group discussion: make a clear point, listen, don't interrupt, support points with examples, and summarise.","Interviews: students must explain their own projects in depth and have honest answers to common HR questions. Aim for many mock interviews.","Soft skills are the common gap — surveys suggest only around half of Indian graduates are strong at communication and critical thinking."],
  toolkit:["Run a resume clinic: every resume reviewed by a faculty member before the first drive.","Set a 30-minute daily aptitude habit with a timed test every week.","Organise faculty and alumni mock-interview panels every week in the final 8 weeks."],
  check:{q:"A student lists a skill on their resume that they can't explain. What's your advice?",o:["Keep it — recruiters won't check","Remove it; interviewers question every line","Add even more skills","Just make the font smaller"],a:1},
  scenes:[
   {tag:"Module 3",title:"Four rounds, four different skills",glyph:"🧩",points:["Aptitude: thinking speed","GD: communication","Technical: depth","HR: attitude & fit"],say:"Module three. Nearly every campus process follows the same shape. Aptitude tests thinking speed. Group discussions test communication. Technical rounds test depth. HR rounds test attitude and fit. Train each one separately."},
   {tag:"Resume",title:"The resume gets seconds, not minutes",glyph:"📄",points:["One page","Role-specific","Quantified results","No fake skills"],say:"Recruiters scan a fresher resume in seconds, and many companies filter them automatically first. Keep it to one clean page, tailor it to the role, quantify outcomes, and never list a skill the student can't defend."},
   {tag:"Aptitude",title:"Little and often wins",glyph:"🧮",points:["30 min daily","Timed mocks","Past papers","Review mistakes"],say:"Many capable students fail the very first aptitude round and never get to show their real skills. The fix is consistency: around thirty minutes a day, timed mock tests, and reviewing every mistake."},
   {tag:"GD & interviews",title:"Practised, not improvised",glyph:"🎤",points:["Clear point","Listen first","Explain your project","10+ mocks"],say:"In group discussions, students should make one clear point, listen, avoid interrupting and summarise. In interviews, they must explain their own project in depth. Nothing builds confidence like repeated mock interviews with faculty and alumni."},
   {tag:"Soft skills",title:"Close the gap inside your classroom",glyph:"🗨️",points:["Present","Defend decisions","Critique peers"],say:"Soft skills are where many graduates fall short. Build them into class: ask students to present, defend their decisions and review each other's work. Every lecture can double as interview practice."}
  ]},
 {title:"Running a placement drive day", sub:"Before, during and after", mins:"6 min",
  intro:"A drive is a live event with a recruiter, dozens or hundreds of students, and a tight clock. Most problems on the day come from something that wasn't checked the day before.",
  takeaways:["Before: circulate the drive notice and job description, verify the eligible list, confirm rooms, projectors, internet and test systems, brief student coordinators, and share reporting time and dress code.","During: take attendance at the pre-placement talk, keep students on schedule, attach a coordinator to each panel, look after the recruiter team, and keep one escalation contact.","Students carry printed resumes, ID and certificate copies, and route everything through the placement cell — no salary negotiation or direct HR contact.","Many institutes don't allow on-the-spot offers; results come officially through the placement office.","After: communicate results promptly to everyone, thank the recruiter, and record their feedback."],
  toolkit:["Use a T-minus checklist: three days before, one day before, and drive morning.","Assign one student coordinator to each interview panel.","Send results and next steps to every participant the same day."],
  check:{q:"When should non-selected students hear about the result?",o:["Never","At the end of the semester","Promptly, ideally the same day","Only if they ask"],a:2},
  scenes:[
   {tag:"Module 4",title:"Drive day is decided the day before",glyph:"⏱️",points:["Venue","Tech check","Student lists","Coordinators"],say:"Module four is drive day. Nearly every drive-day problem, from a dead projector to a missing student list, could have been caught the day before."},
   {tag:"Checklist",title:"The T-minus plan",glyph:"✅",points:["T-3: notice, lists, rooms","T-1: tech test, briefing","Morning: attendance, panels"],say:"Three days out, circulate the job description, confirm the eligible list and book rooms. One day out, test internet and systems and brief student coordinators. On the morning, open attendance early and set up interview panels."},
   {tag:"Students",title:"What to carry, how to behave",glyph:"👔",points:["Printed resumes & ID","Formal dress","Phones silent","No direct HR contact"],say:"Students should carry printed resumes, ID and certificate copies, dress formally, and arrive before reporting time. Remind them not to negotiate pay on the spot or contact the company's HR directly. Everything goes through the placement cell."},
   {tag:"Recruiters",title:"Treat the recruiter as a guest",glyph:"🤝",points:["One point of contact","Tight schedule","Comfort & water","Thank-you note"],say:"Recruiters remember how a campus treated them. Give them one point of contact, keep the schedule tight, and look after their comfort. A smooth day is how you get invited back next year."},
   {tag:"After",title:"Close the loop the same day",glyph:"📬",points:["Official results","Inform every student","Recruiter feedback"],say:"Collect results officially, inform every participant including those not selected, and ask the recruiter for honest feedback. That feedback becomes next season's training plan."}
  ]},
 {title:"Handling multiple companies", sub:"Same day clashes and back-to-back drives", mins:"6 min",
  intro:"The hardest days are when several companies want the same students at once, or drives arrive in quick succession. Without clear rules, students get stuck between clashing interviews and recruiters are left waiting.",
  takeaways:["Decide slotting rules in advance. Many institutes group companies into slots by package and role and release all results together at the end of the slot.","Collect each student's company preferences and any dream-company choice before the slot opens, so clashes are settled by rules, not favours.","On a same-day clash, keep a live clash sheet, stagger rounds, place runners between rooms, and agree priority with each recruiter beforehand.","If a student holds more than one offer from the same slot, give a short fixed window — often about a day — to choose and inform the cell.","For back-to-back days, leave preparation gaps before big recruiters, brief students on each company, and watch for fatigue."],
  toolkit:["Keep a live clash sheet: student, companies, round times, current room.","Agree with every recruiter how you'll handle a student called by two panels at once.","Never let a clash be settled by who shouts loudest — apply the written rule."],
  check:{q:"Two panels call the same student at 10 a.m. What decides where they go first?",o:["Whichever panel calls loudest","The rule and priority agreed in advance","The student's friends","A coin toss"],a:1},
  scenes:[
   {tag:"Module 5",title:"Two companies, one student, same hour",glyph:"🔀",points:["Clashing rounds","Confused students","Waiting recruiters"],say:"Module five. It's ten a.m. Company A wants a student in its technical round, and Company B has just called the same student for HR. Without a plan, someone loses. This module is that plan."},
   {tag:"Structure",title:"Slots and tiers, decided in advance",glyph:"🗂️",points:["Group by package & role","Fixed slot windows","Results at slot end"],say:"Many institutes group companies into slots based on package and role, run each slot in a fixed window, and release all results together at the end of the slot. That removes the pressure to grab the first offer out of panic."},
   {tag:"Before the slot",title:"Collect preferences first",glyph:"📝",points:["Company priority order","Dream choice declared","Locked before slot opens"],say:"Before a multi-company slot, collect each student's company preferences and any dream-company choice, and lock them before the slot opens. Then clashes are settled by a rule the student chose, not by favours."},
   {tag:"On the day",title:"Running a same-day clash",glyph:"🧭",points:["Live clash sheet","Staggered rounds","Runners between rooms","Priority agreed"],say:"On the day, keep a live clash sheet of every student shortlisted by more than one company. Stagger rounds where possible, place student runners between rooms, and agree with recruiters beforehand how a student called by two panels will be handled."},
   {tag:"Multiple offers",title:"Choose, don't hoard",glyph:"✋",points:["Short fixed window","Declare to the cell","Release the other offer"],say:"If results come out together and a student holds two offers, give them a short fixed window, often around a day, to choose and inform the placement cell. Holding offers blocks classmates and damages recruiter trust."},
   {tag:"Different days",title:"Back-to-back drives need recovery",glyph:"🔋",points:["Prep gaps before big drives","Company-specific briefing","Watch for fatigue"],say:"When drives fall on consecutive days, leave preparation time before major recruiters, brief students on each company separately, and watch for exhausted students who need a nudge or a break."}
  ]},
 {title:"Conduct, fairness and discipline", sub:"Rules students respect", mins:"4 min",
  intro:"A single no-show or dishonest resume can cost a whole batch a recruiter. At the same time, rules only earn respect when they are applied the same way to everyone.",
  takeaways:["Common house rules: attend every drive you registered for, keep the resume honest, don't withdraw after being shortlisted, don't contact recruiters directly, and never use unfair means in tests.","Many policies suspend or debar students for repeated no-shows or misconduct. Apply them consistently and proportionately, with a warning first.","Fairness has to be visible: publish eligibility criteria, shortlists and results transparently.","Students should report recruiter misbehaviour to the placement cell rather than handle it alone."],
  toolkit:["Publish a simple penalty ladder: warning, short suspension, longer suspension.","Log every disciplinary decision with the date and reason.","Tell students exactly how to report a problem with a recruiter."],
  check:{q:"Which disciplinary approach works best?",o:["Harsh on some students, lenient on others","Consistent and proportionate, starting with a warning","Ignoring no-shows entirely","A permanent ban for any first offence"],a:1},
  scenes:[
   {tag:"Module 6",title:"One no-show hurts everyone",glyph:"🚫",points:["Recruiter's time","Campus reputation","Next year's slot"],say:"Module six is about conduct. When a registered student skips a drive, the recruiter notices, and so does their HR team when planning next year."},
   {tag:"House rules",title:"The rules most campuses use",glyph:"📋",points:["Attend what you register for","Honest resume","No mid-process withdrawal","No unfair means"],say:"Most placement codes ask students to attend every drive they register for, keep their resume honest, not withdraw after being shortlisted, and never use unfair means in tests."},
   {tag:"Discipline",title:"Consistent, proportionate, documented",glyph:"⚖️",points:["Warning first","Clear penalty ladder","Same rule for everyone"],say:"Discipline only works if it's consistent. Use a clear ladder that starts with a warning, apply the same rule to the topper and the backbencher, and document every decision."},
   {tag:"Both ways",title:"Respect runs in both directions",glyph:"🛡️",points:["Report recruiter issues","Protect student data","Transparent results"],say:"Conduct runs both ways. Students should report any recruiter misbehaviour to the placement cell instead of handling it alone, and the cell must keep processes transparent and student data confidential."}
  ]},
 {title:"Motivating students through the season", sub:"Belief, rejection and wellbeing", mins:"6 min",
  intro:"Placement season is emotionally heavy. Students watch friends get placed, wait anxiously for results, and start believing one rejection says something about their worth. A faculty mentor can change how a student reads that moment.",
  takeaways:["Rebuild belief through small, real wins: specific praise, visible progress, and short goals students can actually hit.","Debrief every rejection within a day: one thing that went well, one thing to fix, and the next opportunity on the calendar.","Use peers and alumni. Small prep groups create accountability, and alumni mentors show students that someone like them made it.","Keep unplaced students moving — upcoming drives, off-campus applications, short skill sprints — so nobody is left idle.","Know the warning signs of real distress and refer. You are a mentor, not a therapist."],
  toolkit:["After each drive, message every non-selected student within 24 hours with one strength and one next step.","Form prep pods of 5–6 students with a weekly target.","Keep your college counsellor's contact and India's Tele-MANAS mental health helpline (14416) handy."],
  check:{q:"What's the best first step after a student is rejected?",o:["Tell them to simply try harder","Debrief: one strength, one fix, next opportunity","Compare them with placed classmates","Give them space for a month"],a:1},
  scenes:[
   {tag:"Module 7",title:"The season gets heavy",glyph:"🌧️",points:["Friends getting placed","Waiting for results","Comparison online"],say:"Module seven. Placement season is emotionally heavy. Students compare themselves with friends, wait anxiously for results, and read every rejection as a verdict on who they are."},
   {tag:"Belief",title:"Small wins rebuild belief",glyph:"🌱",points:["Specific praise","Visible progress","Achievable goals"],say:"When a student has lost belief, a big motivational speech rarely works. What works is small, real wins: specific praise for something they did well, progress they can see, and short goals they can actually hit."},
   {tag:"Rejection",title:"Debrief every rejection",glyph:"🔁",points:["What went well","One thing to fix","Next drive on the calendar"],say:"After a rejection, talk to the student within a day. Name one thing that went well, one thing to fix, and the next opportunity already on the calendar. Rejection becomes feedback, not a full stop."},
   {tag:"Community",title:"Peers and alumni do what lectures can't",glyph:"👥",points:["Prep pods of 5–6","Alumni mentors","Celebrate milestones"],say:"Peer groups and alumni mentors keep students moving. Small prep pods with weekly goals create gentle accountability, and alumni prove that someone from the same benches made it. Celebrate every milestone, not just offers."},
   {tag:"Wellbeing",title:"Know when to refer",glyph:"🆘",points:["Going silent","Hopeless talk","Skipping everything","Refer to a counsellor"],say:"Watch for warning signs: a student going silent, talking hopelessly, or skipping everything. You don't need to be a therapist. Check in privately and connect them with the college counsellor or a helpline like Tele-MANAS."}
  ]},
 {title:"Protecting students from fake offers", sub:"Spot, verify, report", mins:"4 min",
  intro:"Freshers are prime targets for recruitment fraud — excited, inexperienced with HR processes, and hesitant to ask questions. A five-minute check by a faculty member can save a student money and personal data.",
  takeaways:["Genuine employers don't charge for registration, interviews, training, laptops or document verification.","Red flags: free-mail addresses instead of a company domain, an offer with no real interview, an unusually high fresher salary, pressure to pay fast, and conversations only on WhatsApp or Telegram.","Verify through the company's official careers site; some large employers offer online offer-letter verification.","If fraud happens: stop contact, pay nothing more, keep evidence, report on the national cybercrime portal (cybercrime.gov.in) or call 1930, and inform the real company."],
  toolkit:["Route every off-campus offer through a quick faculty or placement-cell check.","Give a 15-minute scam awareness talk before the season starts.","Pin the red-flag list in your department's student group."],
  check:{q:"A 'recruiter' asks a student for ₹2,000 as a document verification fee. This is:",o:["Normal HR practice","A red flag for fraud","Required by law","Fine, since it's refundable"],a:1},
  scenes:[
   {tag:"Module 8",title:"The offer that's too good to be true",glyph:"🎣",points:["Instant selection","Huge package","'Just a small fee'"],say:"Module eight. Freshers are prime targets for fake job offers: excited, inexperienced, and afraid to ask too many questions."},
   {tag:"Red flags",title:"What to teach every student",glyph:"🚩",points:["Any fee demanded","Free-mail address","No real interview","Pay within 24 hours"],say:"Teach students the red flags. Any request for money, whether a registration fee, laptop deposit or verification charge. Emails from free mail accounts instead of the company domain. An offer with no real interview. And pressure to pay immediately."},
   {tag:"Verify",title:"Verify before celebrating",glyph:"🔎",points:["Official careers site","Company verification tools","Ask the placement cell"],say:"Genuine offers can be verified. Check the company's official careers website, use its offer verification service if it has one, and run anything off-campus past the placement cell."},
   {tag:"Report",title:"If it has already happened",glyph:"📞",points:["Stop & don't pay","Save evidence","cybercrime.gov.in or 1930"],say:"If a student has been targeted, they should stop responding, pay nothing more, and save every message and receipt. Report it on the national cybercrime portal or by calling nineteen thirty, and inform the real company."}
  ]},
 {title:"Measuring results and building next year", sub:"Metrics, feedback, alumni", mins:"4 min",
  intro:"Placement work compounds. The numbers you track, the feedback you act on, and the relationships you keep decide whether next season starts stronger.",
  takeaways:["Track a few useful numbers: eligible versus registered students, placement rate by department, round-wise drop-off, offer acceptance, and recruiter return rate.","Feed recruiter feedback directly into training and teaching plans.","Stay in touch with placed alumni — they become mentors, speakers and referrers.","Turn strong recruiter relationships into an industry advisory panel that keeps the curriculum current.","Recruiters keep score: a well-run campus earns better slots next season."],
  toolkit:["Build a one-page season report for your department.","Hold a 45-minute review with the TPO after each season.","Invite two placed alumni back as mentors within three months."],
  check:{q:"Which metric shows where students are falling out of the process?",o:["Round-wise drop-off","Number of rooms booked","Cost of recruiter lunch","Total emails sent"],a:0},
  scenes:[
   {tag:"Module 9",title:"What gets measured gets fixed",glyph:"📊",points:["Registration rate","Round-wise drop-off","Offer acceptance","Recruiter return rate"],say:"Our final module. Track a few numbers that tell you something: how many eligible students registered, where students drop out across rounds, how many offers are accepted, and how many recruiters come back."},
   {tag:"Feedback",title:"Feedback becomes curriculum",glyph:"🔄",points:["Recruiter feedback","Gaps by round","Next year's training plan"],say:"If three recruiters say students can't explain their projects, that's next semester's teaching plan. Close the loop between recruiter feedback and what happens in class."},
   {tag:"Network",title:"Alumni and advisory panels",glyph:"🌐",points:["Alumni mentors & referrers","Industry advisory panel","Stronger recruiter base"],say:"Placed students become your best network. Track their careers, bring them back as mentors, speakers and referrers, and turn strong recruiter relationships into an advisory panel."},
   {tag:"Finish",title:"You're ready for the exam",glyph:"🏅",points:["10 questions","70% to pass","Core5 certificate"],say:"That completes the course. Take the final exam. Score seventy percent or more to earn your Faculty Placement Champion certificate from Core5 Systems and Services. Good luck."}
  ]}
];

export const BANK = [
 {q:"What does a 'one student, one offer' policy usually mean?",o:["Students may hold unlimited offers","Once placed, a student generally exits the process, apart from any dream option the policy allows","Only toppers receive offers","Offers are shared between students"],a:1,e:"Most such policies take a placed student out of further drives, sometimes with one dream-company exception."},
 {q:"Why do many institutes release all results together at the end of a slot?",o:["To slow recruiters down","So students aren't pushed into accepting the first offer in a panic and can choose fairly","To hide results","To save paper"],a:1,e:"Releasing results together lets students choose among offers under a clear rule."},
 {q:"A 'dream company' option typically:",o:["Lets a placed student attempt one clearly better company under the policy","Lets anyone skip the aptitude test","Guarantees an offer","Is decided after results come out"],a:0,e:"It's a single, pre-defined upgrade opportunity for placed students."},
 {q:"When should a student declare their dream-company preference?",o:["After receiving the offer","Before the slot starts","Never","At convocation"],a:1,e:"Preferences are locked before the slot so clashes are settled by rules."},
 {q:"What does a live clash sheet track?",o:["Students' semester marks","Students shortlisted by several companies, with round times and current room","Recruiter salaries","The canteen menu"],a:1,e:"It lets coordinators move students between panels without chaos."},
 {q:"A student holds two offers from the same slot. Typical policy is to:",o:["Hold both for a month","Choose within a short fixed window and inform the placement cell","Accept both","Let the companies decide"],a:1,e:"A short window keeps things fair for classmates and recruiters."},
 {q:"What's the most effective way to build aptitude?",o:["Cram the night before","Short, timed daily practice over months with mistake review","Skip it and focus on coding","Read theory only"],a:1,e:"Consistency beats intensity for aptitude."},
 {q:"In a group discussion, the strongest behaviour is to:",o:["Speak the most","Interrupt to show confidence","Make clear points, listen, build on others and summarise","Stay silent"],a:2,e:"GDs reward clarity and listening, not volume."},
 {q:"Which resume advice fits freshers best?",o:["Three pages with graphics","One clean page, tailored to the role, with quantified outcomes","One resume for every role","List every tool you've heard of"],a:1,e:"Recruiters and filters spend seconds on a fresher resume."},
 {q:"Which task belongs to the day before a drive?",o:["Circulating the job description for the first time","Testing internet and systems and briefing student coordinators","Planning next year's calendar","Releasing results"],a:1,e:"T-1 is for final checks and briefings."},
 {q:"On drive day, students should:",o:["Negotiate salary with the panel","Contact the company HR directly for feedback","Carry printed resumes and ID and route everything through the placement cell","Keep phones ringing"],a:2,e:"All communication with recruiters goes through the cell."},
 {q:"Why treat recruiters as guests?",o:["It's a legal requirement","A smooth experience makes them likelier to return","To get on-the-spot offers","It isn't necessary"],a:1,e:"Campus recruiting is a repeat relationship."},
 {q:"A registered student skips a drive without informing anyone. A sound response is to:",o:["Ignore it","Apply the published policy consistently, starting with the first step of the ladder","Shame them publicly","Ban them permanently at once"],a:1,e:"Consistency and proportion make discipline credible."},
 {q:"A student faces misbehaviour from a recruiter. They should:",o:["Confront the recruiter","Post about it on social media","Report it to the placement cell","Ignore it"],a:2,e:"The cell handles recruiter issues formally."},
 {q:"How do you best re-engage a disengaged student?",o:["A big motivational speech","Small achievable goals and specific praise for real progress","Compare them with toppers","Remove them from the pipeline"],a:1,e:"Small real wins rebuild belief."},
 {q:"Peer prep pods mainly help by:",o:["Replacing faculty","Creating accountability and support","Reducing the number of drives","Guaranteeing offers"],a:1,e:"Peers keep each other moving."},
 {q:"A student talks hopelessly and skips everything. As a faculty mentor you should:",o:["Ignore it","Try to diagnose them","Check in privately and refer them to a counsellor or helpline","Tell them to toughen up"],a:2,e:"Mentors notice and refer; professionals treat."},
 {q:"Which is a sign of a fake job offer?",o:["An email from the company domain after interviews","A request to pay a laptop deposit before joining","An offer that came through the placement cell","Several interview rounds"],a:1,e:"Genuine employers don't charge candidates."},
 {q:"Where can job fraud be reported in India?",o:["Nowhere","The national cybercrime portal or the 1930 helpline","The recruiter's WhatsApp","The college canteen"],a:1,e:"cybercrime.gov.in and 1930 are the official channels."},
 {q:"Recruiter feedback is best used to:",o:["File away","Shape next season's training and teaching","Blame students","Replace recruiters"],a:1,e:"Feedback closes the loop between industry and classroom."}
];
export const EXAM_N = 10, PASS = 7;

